<?xml version="1.0" encoding= "UTF-8" ?>
<!DOCTYPE libreria[
<!ELEMENT libreria (libro+) >
<!ELEMENT libro (titulo,autor,precio,disponible)>
<!ATTLIST libro genero CDATA #REQUIRED> 
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT autor (#PCDATA) >
<!ELEMENT precio (#PCDATA) >
<!ELEMENT disponible (#PCDATA) >
]>
<libreria>
    <libro genero="Ciencia ficcion">
        <titulo>La Fundacion</titulo>
        <autor>Isaac Asimov</autor>
        <precio>25.99</precio>
        <disponible>si</disponible>
    </libro>
    <libro genero="Fantasia">
        <titulo>Juego de tronos</titulo>
        <autor>George R.R Martin</autor>
        <precio>29.99</precio>
        <disponible>no</disponible>
    </libro>
    <libro genero="Aventura">
        <titulo>La isla del tesoro</titulo>
        <autor>Robert Louis Stevenson</autor>
        <precio>18.99</precio>
        <disponible>si</disponible>
    </libro>
</libreria>