<?xml version="1.0" encoding= "UTF-8" ?>
<!DOCTYPE empleados [
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre,apellido,edad,departamento,cargo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>

]>
<empleados>
    <empleado>
        <nombre>Ana</nombre>
        <apellido>Garc√≠a</apellido>
        <edad>30</edad>
        <departamento>Ventas</departamento>
        <cargo>Ejecutivo de ventas</cargo>
    </empleado>
    <empleado>
        <nombre>Luis</nombre>
        <apellido>Rodriguez</apellido>
        <edad>45</edad>
        <departamento>Finanzas</departamento>
        <cargo>Analista financiero</cargo>
    </empleado>
    <empleado>
        <nombre>Maria</nombre>
        <apellido>Lopez</apellido>
        <edad>28</edad>
        <departamento>Marketing</departamento>
        <cargo>Especialista en redes sociales</cargo>
    </empleado>
</empleados>